name: we-1
# Controls when the workflow will run
on: workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: WF1-J1-S1-first step
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: WF1-J1-S2-last step
        run: echo last step.
